name: Deploy Cloud Function
on:
  push:
    branches: [ master ]
env:
  PROJECT: optimal-chimera-388113

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

   
      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{env.PROJECT}}
          service_account_key: ${{secrets.GCP_SA}}
          export_default_credentials: true

      - name: deploy cloud function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: datavigya
          runtime: java11
          project_id: infra-datavigya
          entry_point: functions.helloworld
          timeout: 250

      - name: make the url aunthenticated
        run: |
          gcloud functions add-iam-policy-binding infra-datavigya --member="allUsers" --role="roles/cloudfunctions.invoker"

      - name: test the url
        run: curl "${{ steps.deploy.outputs.url }}"


